UserParameter=pbs.backup.discovery,/usr/share/pbs-zabbix/bin/pbs-zabbix-backup-check discovery
UserParameter=pbs.backup.age[*],/usr/share/pbs-zabbix/bin/pbs-zabbix-backup-check age $1
UserParameter=pbs.backup.laststatus[*],/usr/share/pbs-zabbix/bin/pbs-zabbix-backup-check status $1
